[package]
name = "rsa-encrypt-decrypt-rs"
version = "0.1.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.7"
base85 = "2.0.0"
rand = "0.8.5"
rsa = "0.9.6"
